// Code generated by ent, DO NOT EDIT.

package ent

import (
	"form-survey-cs-service/internal/repository/ent/schema"
	"form-survey-cs-service/internal/repository/ent/task"
	"form-survey-cs-service/internal/repository/ent/tasklog"
	"form-survey-cs-service/internal/repository/ent/taskrecord"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescName is the schema descriptor for name field.
	taskDescName := taskFields[3].Descriptor()
	// task.DefaultName holds the default value on creation for the name field.
	task.DefaultName = taskDescName.Default.(string)
	tasklogFields := schema.TaskLog{}.Fields()
	_ = tasklogFields
	// tasklogDescMessage is the schema descriptor for message field.
	tasklogDescMessage := tasklogFields[1].Descriptor()
	// tasklog.DefaultMessage holds the default value on creation for the message field.
	tasklog.DefaultMessage = tasklogDescMessage.Default.(string)
	taskrecordFields := schema.TaskRecord{}.Fields()
	_ = taskrecordFields
	// taskrecordDescState is the schema descriptor for state field.
	taskrecordDescState := taskrecordFields[1].Descriptor()
	// taskrecord.DefaultState holds the default value on creation for the state field.
	taskrecord.DefaultState = taskrecordDescState.Default.(string)
	// taskrecordDescRetryCount is the schema descriptor for retry_count field.
	taskrecordDescRetryCount := taskrecordFields[2].Descriptor()
	// taskrecord.DefaultRetryCount holds the default value on creation for the retry_count field.
	taskrecord.DefaultRetryCount = taskrecordDescRetryCount.Default.(int)
	trackerFields := schema.Tracker{}.Fields()
	_ = trackerFields
}
