// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"form-survey-cs-service/internal/repository/ent/task"
	"form-survey-cs-service/internal/repository/ent/taskrecord"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (tc *TaskCreate) SetType(s string) *TaskCreate {
	tc.mutation.SetType(s)
	return tc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tc *TaskCreate) SetNillableType(s *string) *TaskCreate {
	if s != nil {
		tc.SetType(*s)
	}
	return tc
}

// SetRowNum sets the "row_num" field.
func (tc *TaskCreate) SetRowNum(i int) *TaskCreate {
	tc.mutation.SetRowNum(i)
	return tc
}

// SetName sets the "name" field.
func (tc *TaskCreate) SetName(s string) *TaskCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tc *TaskCreate) SetNillableName(s *string) *TaskCreate {
	if s != nil {
		tc.SetName(*s)
	}
	return tc
}

// SetPhone sets the "phone" field.
func (tc *TaskCreate) SetPhone(s string) *TaskCreate {
	tc.mutation.SetPhone(s)
	return tc
}

// SetGroup sets the "group" field.
func (tc *TaskCreate) SetGroup(s string) *TaskCreate {
	tc.mutation.SetGroup(s)
	return tc
}

// SetCorps sets the "corps" field.
func (tc *TaskCreate) SetCorps(s string) *TaskCreate {
	tc.mutation.SetCorps(s)
	return tc
}

// SetNillableCorps sets the "corps" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCorps(s *string) *TaskCreate {
	if s != nil {
		tc.SetCorps(*s)
	}
	return tc
}

// SetGender sets the "gender" field.
func (tc *TaskCreate) SetGender(s string) *TaskCreate {
	tc.mutation.SetGender(s)
	return tc
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (tc *TaskCreate) SetNillableGender(s *string) *TaskCreate {
	if s != nil {
		tc.SetGender(*s)
	}
	return tc
}

// SetGeneration sets the "generation" field.
func (tc *TaskCreate) SetGeneration(s string) *TaskCreate {
	tc.mutation.SetGeneration(s)
	return tc
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (tc *TaskCreate) SetNillableGeneration(s *string) *TaskCreate {
	if s != nil {
		tc.SetGeneration(*s)
	}
	return tc
}

// SetRegion sets the "region" field.
func (tc *TaskCreate) SetRegion(s string) *TaskCreate {
	tc.mutation.SetRegion(s)
	return tc
}

// SetRegisteredAt sets the "registered_at" field.
func (tc *TaskCreate) SetRegisteredAt(t time.Time) *TaskCreate {
	tc.mutation.SetRegisteredAt(t)
	return tc
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableRegisteredAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetRegisteredAt(*t)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TaskCreate) SetID(i int) *TaskCreate {
	tc.mutation.SetID(i)
	return tc
}

// SetTaskRecordID sets the "task_record" edge to the TaskRecord entity by ID.
func (tc *TaskCreate) SetTaskRecordID(id int) *TaskCreate {
	tc.mutation.SetTaskRecordID(id)
	return tc
}

// SetNillableTaskRecordID sets the "task_record" edge to the TaskRecord entity by ID if the given value is not nil.
func (tc *TaskCreate) SetNillableTaskRecordID(id *int) *TaskCreate {
	if id != nil {
		tc = tc.SetTaskRecordID(*id)
	}
	return tc
}

// SetTaskRecord sets the "task_record" edge to the TaskRecord entity.
func (tc *TaskCreate) SetTaskRecord(t *TaskRecord) *TaskCreate {
	return tc.SetTaskRecordID(t.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.Name(); !ok {
		v := task.DefaultName
		tc.mutation.SetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.RowNum(); !ok {
		return &ValidationError{Name: "row_num", err: errors.New(`ent: missing required field "Task.row_num"`)}
	}
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Task.name"`)}
	}
	if _, ok := tc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Task.phone"`)}
	}
	if _, ok := tc.mutation.Group(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required field "Task.group"`)}
	}
	if _, ok := tc.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Task.region"`)}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := tc.mutation.RowNum(); ok {
		_spec.SetField(task.FieldRowNum, field.TypeInt, value)
		_node.RowNum = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Phone(); ok {
		_spec.SetField(task.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := tc.mutation.Group(); ok {
		_spec.SetField(task.FieldGroup, field.TypeString, value)
		_node.Group = value
	}
	if value, ok := tc.mutation.Corps(); ok {
		_spec.SetField(task.FieldCorps, field.TypeString, value)
		_node.Corps = value
	}
	if value, ok := tc.mutation.Gender(); ok {
		_spec.SetField(task.FieldGender, field.TypeString, value)
		_node.Gender = value
	}
	if value, ok := tc.mutation.Generation(); ok {
		_spec.SetField(task.FieldGeneration, field.TypeString, value)
		_node.Generation = value
	}
	if value, ok := tc.mutation.Region(); ok {
		_spec.SetField(task.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := tc.mutation.RegisteredAt(); ok {
		_spec.SetField(task.FieldRegisteredAt, field.TypeTime, value)
		_node.RegisteredAt = value
	}
	if nodes := tc.mutation.TaskRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.TaskRecordTable,
			Columns: []string{task.TaskRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
