// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"form-survey-cs-service/internal/repository/ent/tasklog"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TaskLog is the model entity for the TaskLog schema.
type TaskLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 메시지
	Message string `json:"message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskLogQuery when eager-loading is set.
	Edges        TaskLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskLogEdges holds the relations/edges for other nodes in the graph.
type TaskLogEdges struct {
	// TaskRecords holds the value of the task_records edge.
	TaskRecords []*TaskRecord `json:"task_records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskRecordsOrErr returns the TaskRecords value or an error if the edge
// was not loaded in eager-loading.
func (e TaskLogEdges) TaskRecordsOrErr() ([]*TaskRecord, error) {
	if e.loadedTypes[0] {
		return e.TaskRecords, nil
	}
	return nil, &NotLoadedError{edge: "task_records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasklog.FieldID:
			values[i] = new(sql.NullInt64)
		case tasklog.FieldMessage:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskLog fields.
func (tl *TaskLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasklog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tl.ID = int(value.Int64)
		case tasklog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				tl.Message = value.String
			}
		default:
			tl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskLog.
// This includes values selected through modifiers, order, etc.
func (tl *TaskLog) Value(name string) (ent.Value, error) {
	return tl.selectValues.Get(name)
}

// QueryTaskRecords queries the "task_records" edge of the TaskLog entity.
func (tl *TaskLog) QueryTaskRecords() *TaskRecordQuery {
	return NewTaskLogClient(tl.config).QueryTaskRecords(tl)
}

// Update returns a builder for updating this TaskLog.
// Note that you need to call TaskLog.Unwrap() before calling this method if this TaskLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (tl *TaskLog) Update() *TaskLogUpdateOne {
	return NewTaskLogClient(tl.config).UpdateOne(tl)
}

// Unwrap unwraps the TaskLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tl *TaskLog) Unwrap() *TaskLog {
	_tx, ok := tl.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskLog is not a transactional entity")
	}
	tl.config.driver = _tx.drv
	return tl
}

// String implements the fmt.Stringer.
func (tl *TaskLog) String() string {
	var builder strings.Builder
	builder.WriteString("TaskLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tl.ID))
	builder.WriteString("message=")
	builder.WriteString(tl.Message)
	builder.WriteByte(')')
	return builder.String()
}

// TaskLogs is a parsable slice of TaskLog.
type TaskLogs []*TaskLog
