// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"form-survey-cs-service/internal/repository/ent/task"
	"form-survey-cs-service/internal/repository/ent/taskrecord"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TaskRecord is the model entity for the TaskRecord schema.
type TaskRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskRecordQuery when eager-loading is set.
	Edges            TaskRecordEdges `json:"edges"`
	task_task_record *int
	selectValues     sql.SelectValues
}

// TaskRecordEdges holds the relations/edges for other nodes in the graph.
type TaskRecordEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// TaskLogs holds the value of the task_logs edge.
	TaskLogs []*TaskLog `json:"task_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskRecordEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// TaskLogsOrErr returns the TaskLogs value or an error if the edge
// was not loaded in eager-loading.
func (e TaskRecordEdges) TaskLogsOrErr() ([]*TaskLog, error) {
	if e.loadedTypes[1] {
		return e.TaskLogs, nil
	}
	return nil, &NotLoadedError{edge: "task_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskrecord.FieldID, taskrecord.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case taskrecord.FieldState:
			values[i] = new(sql.NullString)
		case taskrecord.ForeignKeys[0]: // task_task_record
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskRecord fields.
func (tr *TaskRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tr.ID = int(value.Int64)
		case taskrecord.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				tr.State = value.String
			}
		case taskrecord.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				tr.RetryCount = int(value.Int64)
			}
		case taskrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_task_record", value)
			} else if value.Valid {
				tr.task_task_record = new(int)
				*tr.task_task_record = int(value.Int64)
			}
		default:
			tr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskRecord.
// This includes values selected through modifiers, order, etc.
func (tr *TaskRecord) Value(name string) (ent.Value, error) {
	return tr.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskRecord entity.
func (tr *TaskRecord) QueryTask() *TaskQuery {
	return NewTaskRecordClient(tr.config).QueryTask(tr)
}

// QueryTaskLogs queries the "task_logs" edge of the TaskRecord entity.
func (tr *TaskRecord) QueryTaskLogs() *TaskLogQuery {
	return NewTaskRecordClient(tr.config).QueryTaskLogs(tr)
}

// Update returns a builder for updating this TaskRecord.
// Note that you need to call TaskRecord.Unwrap() before calling this method if this TaskRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (tr *TaskRecord) Update() *TaskRecordUpdateOne {
	return NewTaskRecordClient(tr.config).UpdateOne(tr)
}

// Unwrap unwraps the TaskRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tr *TaskRecord) Unwrap() *TaskRecord {
	_tx, ok := tr.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskRecord is not a transactional entity")
	}
	tr.config.driver = _tx.drv
	return tr
}

// String implements the fmt.Stringer.
func (tr *TaskRecord) String() string {
	var builder strings.Builder
	builder.WriteString("TaskRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tr.ID))
	builder.WriteString("state=")
	builder.WriteString(tr.State)
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", tr.RetryCount))
	builder.WriteByte(')')
	return builder.String()
}

// TaskRecords is a parsable slice of TaskRecord.
type TaskRecords []*TaskRecord
