// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"form-survey-cs-service/internal/repository/ent/tracker"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrackerCreate is the builder for creating a Tracker entity.
type TrackerCreate struct {
	config
	mutation *TrackerMutation
	hooks    []Hook
}

// SetService sets the "service" field.
func (tc *TrackerCreate) SetService(t tracker.Service) *TrackerCreate {
	tc.mutation.SetService(t)
	return tc
}

// SetNillableService sets the "service" field if the given value is not nil.
func (tc *TrackerCreate) SetNillableService(t *tracker.Service) *TrackerCreate {
	if t != nil {
		tc.SetService(*t)
	}
	return tc
}

// SetLastOne sets the "last_one" field.
func (tc *TrackerCreate) SetLastOne(t time.Time) *TrackerCreate {
	tc.mutation.SetLastOne(t)
	return tc
}

// SetVersion sets the "version" field.
func (tc *TrackerCreate) SetVersion(t time.Time) *TrackerCreate {
	tc.mutation.SetVersion(t)
	return tc
}

// Mutation returns the TrackerMutation object of the builder.
func (tc *TrackerCreate) Mutation() *TrackerMutation {
	return tc.mutation
}

// Save creates the Tracker in the database.
func (tc *TrackerCreate) Save(ctx context.Context) (*Tracker, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TrackerCreate) SaveX(ctx context.Context) *Tracker {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TrackerCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TrackerCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TrackerCreate) defaults() {
	if _, ok := tc.mutation.Service(); !ok {
		v := tracker.DefaultService
		tc.mutation.SetService(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TrackerCreate) check() error {
	if _, ok := tc.mutation.Service(); !ok {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required field "Tracker.service"`)}
	}
	if v, ok := tc.mutation.Service(); ok {
		if err := tracker.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Tracker.service": %w`, err)}
		}
	}
	if _, ok := tc.mutation.LastOne(); !ok {
		return &ValidationError{Name: "last_one", err: errors.New(`ent: missing required field "Tracker.last_one"`)}
	}
	if _, ok := tc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Tracker.version"`)}
	}
	return nil
}

func (tc *TrackerCreate) sqlSave(ctx context.Context) (*Tracker, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TrackerCreate) createSpec() (*Tracker, *sqlgraph.CreateSpec) {
	var (
		_node = &Tracker{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tracker.Table, sqlgraph.NewFieldSpec(tracker.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Service(); ok {
		_spec.SetField(tracker.FieldService, field.TypeEnum, value)
		_node.Service = value
	}
	if value, ok := tc.mutation.LastOne(); ok {
		_spec.SetField(tracker.FieldLastOne, field.TypeTime, value)
		_node.LastOne = value
	}
	if value, ok := tc.mutation.Version(); ok {
		_spec.SetField(tracker.FieldVersion, field.TypeTime, value)
		_node.Version = value
	}
	return _node, _spec
}

// TrackerCreateBulk is the builder for creating many Tracker entities in bulk.
type TrackerCreateBulk struct {
	config
	err      error
	builders []*TrackerCreate
}

// Save creates the Tracker entities in the database.
func (tcb *TrackerCreateBulk) Save(ctx context.Context) ([]*Tracker, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tracker, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrackerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TrackerCreateBulk) SaveX(ctx context.Context) []*Tracker {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TrackerCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TrackerCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
