name: form_survey_app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build
        run: go build -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and release to DockerHub
        env:
          NAME: dnjswo6253 # 계정 명
          REPO: form-survey-cs # 레포 이름
        run: |
          docker build -t $REPO -f ./build/form-survey-cs-service/Dockerfile .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Pull image
        run: docker pull dnjswo6253/form-survey-cs:latest

      # docker-compose.yml 파일을 사용하여 컨테이너 실행
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        env:
          APP: dnjswo6253/form-survey-cs
          COMPOSE: /home/ec2-user/form-survey-cs-service/deployment/docker-compose.yml
        with:
          username: ec2-user
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_KEY}}
          envs: APP, COMPOSE
          script_stop: true
          script: |
            sudo docker compose -f $COMPOSE down --rmi all
            sudo docker pull $/$APP:latest
            sudo docker compose -f $COMPOSE up -d