// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskLog is the predicate function for tasklog builders.
type TaskLog func(*sql.Selector)

// TaskRecord is the predicate function for taskrecord builders.
type TaskRecord func(*sql.Selector)

// Tracker is the predicate function for tracker builders.
type Tracker func(*sql.Selector)
